### ISSUE TITLE
Layers for voxel-to-pillar distillation

### ISSUE THREAD

**Issue by hanin97** [fengjiang5/Knowledge-Distillation-from-Cylinder3D-to-PolarNet#1]
你好，论文中实验细节部分写的"We select the 2nd and 3rd layers in the encoder and decoder..."，`BEV_Unet.py`代码第57行返回的是`[x2, x4, x_up5, x_up3]`，貌似不一致，请问是有什么考量吗？

**Comment by fengjiang5** [comment]
> 你好，论文中实验细节部分写的"We select the 2nd and 3rd layers in the encoder and decoder..."，`BEV_Unet.py`代码第57行返回的是`[x2, x4, x_up5, x_up3]`，貌似不一致，请问是有什么考量吗？

您好，非常感谢您的提问。在我看来选择哪几层来进行蒸馏实际上几乎不会有什么影响，个人尝试过不同的层发现差距非常小。选择哪几层特征进行蒸馏相较于可能对显存占用的影响更大....

**Comment by hanin97** [comment]
谢谢，那选择的层数量对结果影响大吗？

**Comment by hanin97** [comment]
> > 你好，论文中实验细节部分写的"We select the 2nd and 3rd layers in the encoder and decoder..."，`BEV_Unet.py`代码第57行返回的是`[x2, x4, x_up5, x_up3]`，貌似不一致，请问是有什么考量吗？
> 
> 您好，非常感谢您的提问。在我看来选择哪几层来进行蒸馏实际上几乎不会有什么影响，个人尝试过不同的层发现差距非常小。选择哪几层特征进行蒸馏相较于可能对显存占用的影响更大....

谢谢，那选择的层数量对结果影响大吗？

**Comment by fengjiang5** [comment]
> > > 你好，论文中实验细节部分写的"We select the 2nd and 3rd layers in the encoder and decoder..."，`BEV_Unet.py`代码第57行返回的是`[x2, x4, x_up5, x_up3]`，貌似不一致，请问是有什么考量吗？
> > 
> > 
> > 您好，非常感谢您的提问。在我看来选择哪几层来进行蒸馏实际上几乎不会有什么影响，个人尝试过不同的层发现差距非常小。选择哪几层特征进行蒸馏相较于可能对显存占用的影响更大....
> 
> 谢谢，那选择的层数量对结果影响大吗？

因为这部分占用显存比较多，我只试过取一层与两层，对效果的影响不会很大（加大epoch之后）。

**Comment by fengjiang5** [comment]
> > > 你好，论文中实验细节部分写的"We select the 2nd and 3rd layers in the encoder and decoder..."，`BEV_Unet.py`代码第57行返回的是`[x2, x4, x_up5, x_up3]`，貌似不一致，请问是有什么考量吗？
> > 
> > 
> > 您好，非常感谢您的提问。在我看来选择哪几层来进行蒸馏实际上几乎不会有什么影响，个人尝试过不同的层发现差距非常小。选择哪几层特征进行蒸馏相较于可能对显存占用的影响更大....
> 
> 谢谢，那选择的层数量对结果影响大吗？

因为这部分占用显存比较多，我只试过取一层与两层，对效果的影响不会很大（加大epoch之后）。
